# This file allows you to customize what lints HEMTT will use.
# See https://hemtt.dev/configuration/lints.html for full documentation.

# Example: Ban macros that are only used in debug.
[sqf.banned_macros]
options.release = [
    "DEBUG_MODE_FULL", "DISABLE_COMPILE_CACHE"
]

[stringtables.usage]
options.ignore_duplicate = true

[config.file_type]
options.allow_no_extension = true

[sqf.undefined]
enabled = true
options.check_orphan_code = false

[sqf.unused]
#enabled = true #many false positives without DEBUG_MODE_FULL
options.check_params = false

[sqf.not_private]
#enabled = true