name = "Selkie-Liberation"
author = "Violets, [GREUH] Zbug & McKeewa, KP Liberation Dev Team, FatRefrigerator"
prefix = "slklib"
mainprefix = "z"

# Configures what files (other than your mod) will be included in the final build.
[files]
include = [
    "LICENSE",
    "README.md",
    "CHANGELOG.md"
]

# Configures whether git hash will be included in version numbers.
[version]
git_hash = 0
major = 1
minor = 0
patch = 1
build = 0